### PR TITLE
Allow injected 'window'

### PR DESCRIPTION
**Pull request by davidturissini**
The `select` method validated that the `element` passed into the function was an `instanceof` `window.HTMLElement`. This check fails if the element lives under an iframe's `contentWindow`.  I added another option to explicitly set the `window` object.

### CODE REVIEW

**Comment by black-snow** [comment]
+1, my issue exactely

**Comment by davidturissini** [comment]
@black-snow 
```js
import { select } from 'optimal-select';


const iframe = document.querySelector('iframe');
const element = iframe.contentWindow.document.querySelector('div');

const selector = select(element, {
  global: iframe.contentWindow
});

```

**Comment by davidturissini** [comment]
Another way to resolve this would be to remove the `instanceof` checks and instead check to see if `element.nodeType` is defined and is equal to 1 or 3. (https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType)

I think this would be a better solution because it removes the necessity of hacking in a `window` object and still does proper element checking.

@Autarc @black-snow  thoughts?

**Comment by black-snow** [comment]
@davidturissini sounds good to me, the less there is to do in order to get it to work the better :)

**Comment by Autarc** [comment]
@davidturissini Good call, thanks for mentioning it. [Replaced the element validation](https://github.com/Autarc/optimal-select/commit/b389954a3ed1fbcef4ab1f43c55044b598574700) with checking the nodeTypes instead. Should now work in every DOM environment.

**Comment by davidturissini** [comment]
:+1: closing this

**Pull request closed without merging**
